#pragma once

// This file is generated by the TranslatR application. Do not edit it directly or modification will be overwritten!

enum class Language
{
	english,
	french,
	COUNT
};

enum class LocID
{
	language,		// Language
	english,		// English
	french,		// French
	COUNT
};
