#pragma once

// This file is generated by the TranslatR application. Do not edit it directly or modification will be overwritten!

enum class Language
{
	english,
	french,
	spanish,
	COUNT
};

enum class LocID
{
	yes,		// yes
	no,		// no
	long_sentense,		// This is an example of long sentense to see how well it would fit in the json file.
	some_example,		// Hello World!
	COUNT
};
